# Generated by Django 2.2.15 on 2021-03-30 04:07

from django.db import migrations, models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateVirtual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255, unique=True, verbose_name='course')),
                ('AdicText', models.CharField(max_length=100, verbose_name='Texto Adicional')),
                ('Format', models.CharField(default='virtual_labx', max_length=30, verbose_name='Formato')),
                ('Chours', models.IntegerField(default=0, verbose_name='Horas Curso')),
            ],
            options={
                'ordering': ('course_id',),
            },
        ),
    ]
